---
- name: Install common packages on Debian family
  ansible.builtin.apt:
    name: '{{ prep_common_packages }}'
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"
- name: Install common packages on RedHat family
  ansible.builtin.dnf:
    name: '{{ prep_common_packages }}'
    state: present
  when: ansible_os_family == "RedHat"
- name: Install tshark on Debian family
  ansible.builtin.apt:
    name: '{{ prep_tshark_package }}'
    state: present
  when: [ansible_os_family == "Debian", prep_install_tshark | bool]
- name: Install tshark on RedHat family
  ansible.builtin.dnf:
    name: '{{ prep_tshark_package }}'
    state: present
  when: [ansible_os_family == "RedHat", prep_install_tshark | bool]
